favorite_sport = []
favorite_sport.append("table tannis")
favorite_sport.append("swim")
favorite_sport.append("baseball")
favorite_sport.append("basketball")
print(favorite_sport)
favorite_sport.insert(0,"jump rope")
favorite_sport.insert(2,10)
favorite_sport.remove("basketball")
print(favorite_sport)